title: Enquête collective - La Vie Sociale des Données
description: Nous sommes cinq étudiants de Sciences Po qui avons étudié la quantification du bonheur et les index qui lui sont reliés. Bienvenue !
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
